In [1]:
import numpy as np
from astropy.io import fits

In [2]:
# Write a .fits file with unit of electrons
hdul = fits.open(r"Rommulus_lens.fits")
t = 600 # in s
electrons_arr = hdul[0].data*t
hdue = fits.PrimaryHDU(electrons_arr)
hdue.header.update(hdul[0].header)
hdue.writeto(r"Rommulus_lens_electrons.fits", overwrite=True)

## Create noise map in units of e

In [3]:
hdul = fits.open(r"Rommulus_lens.fits")
t = 600 # in s

## SD of sky background
sd = 0.0654895398066939
rand_noise = sd*t
print(rand_noise)
phot_arr = hdul[0].data*t
print(phot_arr)
def phot_noise_arr(array):
    phot_valid_array = np.where(array > (2.5*rand_noise), array, 0)
    return phot_valid_array
phot_valid_arr = phot_noise_arr(phot_arr)
print(phot_valid_arr)

rand_noise_sd_arr = np.full((125, 125), rand_noise)
phot_noise_sd_arr = np.sqrt(phot_valid_arr)
print(rand_noise_sd_arr)
print(phot_noise_sd_arr)

tot_noise = np.sqrt(rand_noise_sd_arr**2 + phot_noise_sd_arr**2)

39.293723884016345
[[  8.74250492  27.74738062  93.67721264 ...  36.44149541 -38.32781568
  -15.46520011]
 [-25.86585068  16.28985867 -14.50777008 ...  39.90054737 -21.66549896
   12.51736224]
 [ 43.53302567 -67.83060477  10.89816515 ...  46.85685177  80.57006675
  -52.30630439]
 ...
 [ 70.04118315 -24.45736033  49.92050638 ...  18.1856721   67.98713918
   -5.77783136]
 [ 31.11711583 -10.61462975 -26.50181175 ...  -3.58912981  49.56024272
   71.85989291]
 [-10.0909797  -36.38916334 -33.73520632 ... -55.13204229  -1.24310266
  -31.82955237]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[39.29372388 39.29372388 39.29372388 ... 39.29372388 39.29372388
  39.29372388]
 [39.29372388 39.29372388 39.29372388 ... 39.29372388 39.29372388
  39.29372388]
 [39.29372388 39.29372388 39.29372388 ... 39.29372388 39.29372388
  39.29372388]
 ...
 [39.29372388 39.29372388 39.29372388 ... 39.2937

In [4]:
# # Write cutout as a fits file
hducutout = fits.PrimaryHDU(tot_noise)
hducutout.header.update(hdul[0].header)
# Write cutout with wcs info to file
hducutout.writeto(r"noise_map.fits", overwrite=True)

# Convert e- into counts

In [5]:
gain = 1.6
count_arr = electrons_arr / gain
hducounts = fits.PrimaryHDU(count_arr)
hducounts.header.update(hdul[0].header)
hducounts.writeto(r"counts.fits", overwrite=True)

# Convert noise map into e- unit

In [6]:
noise_c = tot_noise / gain
hdunoisec = fits.PrimaryHDU(noise_c)
hdunoisec.header.update(hdul[0].header)
hducounts.writeto(r"noise_c.fits", overwrite=True)

In [7]:
print(noise_c)
print(tot_noise)

[[24.55857743 24.55857743 24.55857743 ... 24.55857743 24.55857743
  24.55857743]
 [24.55857743 24.55857743 24.55857743 ... 24.55857743 24.55857743
  24.55857743]
 [24.55857743 24.55857743 24.55857743 ... 24.55857743 24.55857743
  24.55857743]
 ...
 [24.55857743 24.55857743 24.55857743 ... 24.55857743 24.55857743
  24.55857743]
 [24.55857743 24.55857743 24.55857743 ... 24.55857743 24.55857743
  24.55857743]
 [24.55857743 24.55857743 24.55857743 ... 24.55857743 24.55857743
  24.55857743]]
[[39.29372388 39.29372388 39.29372388 ... 39.29372388 39.29372388
  39.29372388]
 [39.29372388 39.29372388 39.29372388 ... 39.29372388 39.29372388
  39.29372388]
 [39.29372388 39.29372388 39.29372388 ... 39.29372388 39.29372388
  39.29372388]
 ...
 [39.29372388 39.29372388 39.29372388 ... 39.29372388 39.29372388
  39.29372388]
 [39.29372388 39.29372388 39.29372388 ... 39.29372388 39.29372388
  39.29372388]
 [39.29372388 39.29372388 39.29372388 ... 39.29372388 39.29372388
  39.29372388]]


In [8]:
print(count_arr)
print(electrons_arr)

[[  5.46406558  17.34211289  58.5482579  ...  22.77593463 -23.9548848
   -9.66575007]
 [-16.16615668  10.18116167  -9.0673563  ...  24.93784211 -13.54093685
    7.8233514 ]
 [ 27.20814104 -42.39412798   6.81135322 ...  29.28553235  50.35629172
  -32.69144025]
 ...
 [ 43.77573947 -15.28585021  31.20031649 ...  11.36604506  42.49196199
   -3.6111446 ]
 [ 19.44819739  -6.63414359 -16.56363234 ...  -2.24320613  30.9751517
   44.91243307]
 [ -6.30686231 -22.74322709 -21.08450395 ... -34.45752643  -0.77693916
  -19.89347023]]
[[  8.74250492  27.74738062  93.67721264 ...  36.44149541 -38.32781568
  -15.46520011]
 [-25.86585068  16.28985867 -14.50777008 ...  39.90054737 -21.66549896
   12.51736224]
 [ 43.53302567 -67.83060477  10.89816515 ...  46.85685177  80.57006675
  -52.30630439]
 ...
 [ 70.04118315 -24.45736033  49.92050638 ...  18.1856721   67.98713918
   -5.77783136]
 [ 31.11711583 -10.61462975 -26.50181175 ...  -3.58912981  49.56024272
   71.85989291]
 [-10.0909797  -36.38916334 -33.73